name: Deployment

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get repo
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "^1.22"

      - name: Install packages
        run: go install

      - name: Test output
        run: |
          joke-cli help
          joke-cli generate -n 5
          joke-cli generate --number=5
